name: Unit Tests (Lab04)
on:
  push:
    paths:
      - 'Lab04/AnimatedSprite.cpp'
jobs:
  runtest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Build and run tests
        run: bash Scripts/tests.sh -xe
        env:
          LAB_TO_TEST: Lab04
